<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-J3AJHTH" ignored="1" name="Personal Loan" tests="5" failures="1" timestamp="14 Mar 2019 15:29:29 GMT" time="0.097" errors="0">
  <testcase name="Demo" time="0.013" classname="test.day1">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.day1.Demo(day1.java:20)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- Demo -->
  <testcase name="pload" time="0.001" classname="test.day2"/>
  <testcase name="LoginAPIHomeLoan" time="0.007" classname="test.day4"/>
  <testcase name="MobileLoginHomeLoan" time="0.001" classname="test.day4"/>
  <testcase name="WebloginHomeLoan" time="0.003" classname="test.day4"/>
  <testcase name="SecondTest2" time="0.0" classname="test.day1">
    <ignored/>
  </testcase> <!-- SecondTest2 -->
</testsuite> <!-- Personal Loan -->
